
#!/bin/bash

echo ""
echo "System Report for $(hostname) generated by $(whoami), on $(date)"
echo ""

echo "System Information"
echo "------------------"

# OS info
source /etc/os-release
echo "OS: $PRETTY_NAME"

# Uptime
echo "Uptime: $(uptime -p)"

# CPU
CPU=$(lscpu | grep "Model name" )
echo "CPU: $CPU"

# RAM
RAM=$(free -h | awk '/Mem:/ {print $2}')
echo "RAM: $RAM"

# Disk info
echo -n "Disk(s): "
lsblk -d -o NAME,SIZE,MODEL | tail -n +2

# Video card
VIDEO=$(lspci | grep -i vga | cut -d':' -f3 | sed 's/^ *//')
echo "Video: $VIDEO"

# Network info
HOST_IP=$(ip route get 8.8.8.8 | awk '{print $7; exit}')
GATEWAY=$(ip route | awk '/default/ {print $3}')
DNS=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -1)

echo "Host Address: $HOST_IP"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS"

echo ""
echo "System Status"
echo "-------------"

# Users logged in
echo "Users Logged In: $(who | awk '{print $1}' | sort -u | paste -sd, -)"

# Disk space
echo "Disk Space:"
df -h | awk '$NF=="/" || $NF ~ /^\/mnt/ {print $6, $4}'

# Process count
echo "Process Count: $(ps aux | wc -l)"

# Load averages
echo "Load Averages: $(uptime | awk -F'load average:' '{print $2}')"

# Network ports
echo -n "Listening Network Ports: "
ss -tuln | awk 'NR>1 {print $5}' | cut -d':' -f2 | sort -u | paste -sd, -

# UFW status
echo "UFW $(sudo ufw status | head -1)"

echo ""
